// <auto-generated />
namespace CronReporting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sms_received_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sms_received_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201704190848147_sms_received_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
